name: Build macOS M1 CopasiUI

on:
  workflow_dispatch:
  release:
    types:
    - published
    
jobs:
  build_gui:
    name: Test building CopasiUI
    runs-on: [self-hosted, macOS, ARM64]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules

    - name: restore HEAD
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: |
        git checkout release/Version-4.38

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion --force

    - name: get build tool script
      shell: bash
      run: |
        git clone https://github.com/copasi/build-system build-system-arm
        cd build-system-arm
        git checkout independent-from-home

    - name: Run build
      run: |
        export BUILD_SYSTEM_HOME=$(realpath .)
        source build-system-arm/profile/darwin-arm
        # emerge
        install-dependencies
        release --branch release/Version-4.38 --comment stable --noscp

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: build-system-arm/packages/setup.release/*.dmg
        name: COPASI