name: Build M1 Linux Wheels

env:
  copasi_branch: release/Version-4.40

on:
  workflow_dispatch:
  release:
    types:
    - published
    
jobs:
  build_wheels:
    name: Wheel on for Linux-m1
    runs-on: [self-hosted, linux, ARM64]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules
    
    - name: restore HEAD
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: |
        git checkout $copasi_branch

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion

    - name: Run docker
      run: |
        mkdir wheelhouse
        cp /home/ubuntu/libuuid-1.0.3.tar.gz . 
        cp /home/ubuntu/build_pycopasi.sh . 
        sudo docker run --rm -v `pwd`:/io quay.io/pypa/manylinux2014_aarch64 /io/build_pycopasi.sh

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
        name: COPASI