name: Build Wheels

on:
  workflow_dispatch:
  release:
    types:
    - published
    
jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }} for ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macos-10.15]
        python_version: ['cp37-*', 'cp38-*', 'cp39-*', 'cp310-*']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules
        
    - name: Add msbuild to PATH (Windows)
      if: matrix.os == 'windows-2019'
      uses: ilammy/msvc-dev-cmd@v1.6.0
    
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: restore HEAD
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: |
        git checkout release/Version-4.36

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion

    - name: Copy setup.py
      run: |
        cp copasi_source/copasi/bindings/python/setup.py .

    - uses: pypa/cibuildwheel@v2.4.0
      env:
          CIBW_BUILD: ${{ matrix.python_version }}
          CIBW_BUILD_FRONTEND: "build"
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ENVIRONMENT: COPASI_SRC_DIR=copasi_source COPASI_DEP_DIR=copasi-dependencies COPASI_DEP_SRC=copasi-dependencies
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_GENERATOR=Ninja COPASI_SRC_DIR=copasi_source COPASI_DEP_DIR=copasi-dependencies COPASI_DEP_SRC=copasi-dependencies 
          CIBW_BEFORE_BUILD_LINUX: scripts/install_uuid.sh
          CIBW_SKIP: "*-musllinux*"

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
        name: COPASI-${{ matrix.os }}
