name: Build Wheels

on:
  workflow_dispatch:
  release:
    types:
    - published
    
jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }} for ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2019, macos-10.15]
        python_version: ['cp37-*', 'cp38-*', 'cp39-*', 'cp310-*']

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion

    - name: Copy setup.py
      run: |
        cp copasi_source/copasi/bindings/python/setup.py .

    - uses: pypa/cibuildwheel@v2.3.1
      env:
          CIBW_BUILD: ${{ matrix.python_version }}
          CIBW_ARCHS_MACOS: x86_64 arm64
          CIBW_ENVIRONMENT: COPASI_SRC_DIR=./copasi_source COPASI_DEP_DIR=./copasi-dependencies CMAKE_GENERATOR=Ninja

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
        name: COPASI-${{ matrix.os }}
