name: Build Wheels

env:
  copasi_branch: release/Version-4.45

on:
  workflow_dispatch:
  release:
    types:
    - published
    
jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }} for ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13]
        python_version: ['cp39-*', 'cp310-*', 'cp311-*', 'cp312-*', 'cp313-*']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules
    
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: restore HEAD
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: |
        git checkout release/Version-4.45

    - name: Install gawk on mac
      if: matrix.os == 'macos-13'
      shell: bash
      run: brew install gawk

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion

    - name: Copy setup.py
      run: |
        cp copasi_source/copasi/bindings/python/setup.py .

    - uses: pypa/cibuildwheel@v2.21.3
      env:
          CIBW_BUILD: ${{ matrix.python_version }}
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BEFORE_BUILD_MACOS: brew install swig
          CIBW_ENVIRONMENT: COPASI_SRC_DIR=copasi_source COPASI_DEP_DIR=copasi-dependencies COPASI_DEP_SRC=copasi-dependencies
          CIBW_BEFORE_BUILD_LINUX: scripts/install_uuid.sh
          CIBW_SKIP: "*-musllinux*"

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: COPASI-${{ matrix.os }}-${{ strategy.job-index }}

  build_windows_wheels:
    name: Wheel on Windows ${{ matrix.arch }} for ${{ matrix.python_version }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        arch: [AMD64, x86 ]
        python_version: ['cp39-*', 'cp310-*', 'cp311-*', 'cp312-*', 'cp313-*']

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: recursive  # Optional, use if you have submodules
        
    - name: Add msbuild to PATH (Windows)
      uses: ilammy/msvc-dev-cmd@v1
      with: 
        arch: ${{ matrix.arch }}
    
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: restore HEAD
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: |
        git checkout release/Version-4.45

    - name: Update COPASI Version
      shell: bash
      working-directory: ${{github.workspace}}/copasi_source
      run: ./gitTools/UpdateCopasiVersion

    - name: Copy setup.py
      run: |
        cp copasi_source/copasi/bindings/python/setup.py .

    - uses: pypa/cibuildwheel@v2.21.3
      env:
          CIBW_BUILD: ${{ matrix.python_version }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT: CMAKE_GENERATOR=Ninja COPASI_SRC_DIR=copasi_source COPASI_DEP_DIR=copasi-dependencies COPASI_DEP_SRC=copasi-dependencies 

    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        path: wheelhouse/*.whl
        name: COPASI-Windows-${{ matrix.arch }}-${{ strategy.job-index }}
